### ISSUE TITLE
TypeError: isObject is not a function

### ISSUE THREAD

**Issue by sayjeyhi** [kis/chartify#27]
I do not know why , but in just fresh install , tried the getstarted exmaple , and this error happened :
```bash
isObject is not a function
TypeError: isObject is not a function
    at Object../packages/chartify/node_modules/core-js/internals/document-create-element.js (http://localhost:5555/vendors~main.b73f54e089b974d06746.bundle.js:88469:14)
    at __webpack_require__ (http://localhost:5555/runtime~main.b73f54e089b974d06746.bundle.js:791:30)
    at fn (http://localhost:5555/runtime~main.b73f54e089b974d06746.bundle.js:151:20)
    at Object../packages/chartify/node_modules/core-js/internals/ie8-dom-define.js (http://localhost:5555/vendors~main.b73f54e089b974d06746.bundle.js:88971:21)
    at __webpack_require__ (http://localhost:5555/runtime~main.b73f54e089b974d06746.bundle.js:791:30)
    at fn (http://localhost:5555/runtime~main.b73f54e089b974d06746.bundle.js:151:20)
    at Object../packages/chartify/node_modules/core-js/internals/object-define-property.js (http://localhost:5555/vendors~main.b73f54e089b974d06746.bundle.js:89833:22)
    at __webpack_require__ (http://localhost:5555/runtime~main.b73f54e089b974d06746.bundle.js:791:30)
    at fn (http://localhost:5555/runtime~main.b73f54e089b974d06746.bundle.js:151:20)
    at Object../packages/chartify/node_modules/core-js/modules/es.object.define-property.js (http://localhost:5555/vendors~main.b73f54e089b974d06746.bundle.js:91801:34)
```

I am using `"chartify": "^3.4.0"` and `storybook`

**Comment by Pratyakshshiv** [comment]
is this issue still open?
